name: CI Pipeline

On:
 Push:
   branches:
     - main
Jobs:
  test:
    runs-on: Ubuntu-latest

    steps:
      -name: checkout code
      uses: actions/checkout@v4

      -name: Say Hello
      run: echo "Hello Github Actions"


