name: Enterprise Banking API CI/CD

on:
  pull_request:
    branches:
      - main

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run Linter
        run: flake8 app/

  unit-tests:

    runs-on: ubuntu-latest

    needs: lint

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests/

  integration-tests:

    runs-on: ubuntu-latest

    needs: unit-tests

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Integration Tests
        run: pytest integration_tests/

  docker-build:

    runs-on: ubuntu-latest

    needs: integration-tests

    steps:

      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t banking-api:${{ github.sha }} .

  docker-scan:

    runs-on: ubuntu-latest

    needs: docker-build

    steps:

      - name: Scan Docker Image
        run: |
          echo "Run Trivy Scan Here"

  push-image:

    runs-on: ubuntu-latest

    needs: docker-scan

    steps:

      - name: Login to Docker Registry
        run: |
          echo "Authenticate to Docker Hub or Amazon ECR"

      - name: Push Docker Image
        run: |
          echo "docker push banking-api:${{ github.sha }}"

  deploy-dev:

    runs-on: ubuntu-latest

    needs: push-image

    steps:

      - name: Deploy to Development
        run: |
          echo "Deploy application to Development Environment"

  smoke-test:

    runs-on: ubuntu-latest

    needs: deploy-dev

    steps:

      - name: Smoke Test
        run: |
          echo "Verify Login API"
          echo "Verify Health Endpoint"

  approval:

    runs-on: ubuntu-latest

    needs: smoke-test

    environment:
      name: production

    steps:

      - name: Await Manual Approval
        run: echo "Waiting for approval"

  deploy-production:

    runs-on: ubuntu-latest

    needs: approval

    steps:

      - name: Deploy Production
        run: |
          echo "Deploy Banking API to Production"